[package]
name = "hangman-data"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]
#clippy = "*"
dotenv = "*"
dotenv_macros = "*"
postgres = "*"
r2d2 = "*"
r2d2_postgres = "*"
serde = "*"